-- NOTE: Template was generated by DRFront automatically.

library IEEE;
use IEEE.std_logic_1164.ALL;
use IEEE.std_logic_unsigned.ALL;

entity DR_ENTITY_NAME is
-- USER_PORT
end DR_ENTITY_NAME;

architecture RTL of DR_ENTITY_NAME is


begin


end RTL;
