// NOTE: Template was generated by DRFront automatically.

module DR_TOP (
    input  logic [15:0] SW,
    input  logic        BTNC, BTNL, BTNR, BTNU, BTND,
    input  logic        CLK, RST,
    output logic [15:0] LD,
    output logic  [7:0] AN,
    output logic        CA, CB, CC, CD, CE, CF, CG, DP);

// USER_SIGNAL_PREFIX

// USER_INSTANCE_PREFIX

endmodule