-- NOTE: This file is generated by DRFront automatically. Do not modify this file.

library IEEE;
use IEEE.std_logic_1164.ALL;

entity DR_TOP is
    port ( SW                             : in  std_logic_vector(15 downto 0);
           BTNC, BTNL, BTNR, BTNU, BTND   : in  std_logic;
           CLK, RST                       : in  std_logic;
           LD                             : out std_logic_vector(15 downto 0);
           AN                             : out std_logic_vector(7 downto 0);
           CA, CB, CC, CD, CE, CF, CG, DP : out std_logic);
end DR_TOP;

architecture STRUCTURE of DR_TOP is
-- USER_COMPONENT
begin
-- USER_INSTANCE
end STRUCTURE;
