common::send_msg_id "DRFront-011" "INFO" "Running a generate-bitstream script generated by DRFront..."
set last_wd [ pwd ]
cd [ file dirname [ file normalize [ info script ] ] ]
source ./OpenProject.tcl

reset_runs synth_1
launch_runs impl_1
wait_on_run impl_1
open_run impl_1
write_bitstream -force ${top_module_name}_${project_name}.bit
close_project

if { $script_mode ne "gui" } {
  stop_gui
}
cd $last_wd