common::send_msg_id "DRFront-021" "INFO" "Running an open-hardware script generated by DRFront..."
set script_mode $rdi::mode
if { $script_mode ne "gui" } {
  start_gui
}
cd [ file dirname [ file normalize [ info script ] ] ]
open_hw_manager
