//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRFront.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DRFront.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   start_gui
        ///create_project -force $project_name . -part xc7a100tcsg324-1
        ///set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
        ///add_files -norecurse $source_files
        ///set_property top DR_TOP [get_filesets sources_1]
        ///update_compile_order -fileset sources_1
        ///set_property -name {STEPS.SYNTH_DESIGN.ARGS.MORE OPTIONS} -value {-mode out_of_context} -objects [get_runs synth_1]
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CREATE_PROJECT {
            get {
                return ResourceManager.GetString("CREATE_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   start_gui
        ///create_project -force $project_name . -part xc7a100tcsg324-1
        ///set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
        ///add_files -norecurse $source_files
        ///set_property SOURCE_SET sources_1 [get_filesets sim_1]
        ///add_files -fileset sim_1 -norecurse $testbench_file
        ///set_property TOP DR_TESTBENCH [get_filesets sim_1]
        ///update_compile_order -fileset sim_1
        ///set_property STEPS.SYNTH_DESIGN.ARGS.FLATTEN_HIERARCHY none [get_runs synth_1]
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CREATE_SIMULATION {
            get {
                return ResourceManager.GetString("CREATE_SIMULATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -- NOTE: Template was generated by DRFront automatically.
        ///
        ///library IEEE;
        ///use IEEE.std_logic_1164.ALL;
        ///use IEEE.std_logic_unsigned.ALL;
        ///
        ///entity DR_ENTITY_NAME is
        ///-- ENTITY_PORT
        ///end DR_ENTITY_NAME;
        ///
        ///architecture RTL of DR_ENTITY_NAME is
        ///
        ///
        ///begin
        ///
        ///
        ///end RTL;
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DR_TEMPLATE {
            get {
                return ResourceManager.GetString("DR_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -- NOTE: Template was generated by DRFront automatically.
        ///
        ///library IEEE;
        ///use IEEE.std_logic_1164.ALL;
        ///use IEEE.std_logic_unsigned.ALL;
        ///
        ///entity DR_TESTBENCH is
        ///end DR_TESTBENCH;
        ///
        ///architecture TEST of DR_TESTBENCH is
        ///-- USER_COMPONENT
        ///
        ///-- USER_SIGNAL
        ///
        ///begin
        ///-- USER_UUT
        ///
        ///-- vvv Define waveforms of input signals vvv
        ///
        ///
        ///-- ^^^ Define waveforms of input signals ^^^
        ///end TEST;
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DR_TESTBENCH {
            get {
                return ResourceManager.GetString("DR_TESTBENCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -- NOTE: This file is generated by DRFront automatically. Do not modify this file.
        ///
        ///library IEEE;
        ///use IEEE.std_logic_1164.ALL;
        ///
        ///entity DR_TOP is
        ///    port ( SW                             : in  std_logic_vector(15 downto 0);
        ///           BTNC, BTNL, BTNR, BTNU, BTND   : in  std_logic;
        ///           CLK, RST                       : in  std_logic;
        ///           LD                             : out std_logic_vector(15 downto 0);
        ///           AN                             : out std_logic_vector(7 downto 0);
        ///           CA [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DR_TOP {
            get {
                return ResourceManager.GetString("DR_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   start_gui
        ///open_checkpoint $checkpoint_base
        ///read_checkpoint -cell [get_cells DR] $checkpoint_proj
        ///opt_design
        ///place_design
        ///route_design
        ///write_bitstream -force ${project_name}.bit
        ///stop_gui に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GENERATE_BITSTREAM {
            get {
                return ResourceManager.GetString("GENERATE_BITSTREAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   start_gui
        ///open_hw_manager
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OPEN_HARDWARE {
            get {
                return ResourceManager.GetString("OPEN_HARDWARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   start_gui
        ///open_project ${project_name}.xpr
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OPEN_PROJECT {
            get {
                return ResourceManager.GetString("OPEN_PROJECT", resourceCulture);
            }
        }
    }
}
